In [1]:
import pandas as pd
import os

# Read the text file into a DataFrame
pair_relation_best = pd.read_csv('/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/task1_finalPerformance/pair_relation_best.txt', sep='\t')

# Now, pair_relation_best_df contains the data from the text file
unique_pair_relation = pd.read_csv("/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/unique_pair_relation.txt", sep='\t')

In [2]:
unique_pair_relation.head()

                Identity_Type Identifier
0              ChemicalEntity    D014867
1  DiseaseOrPhenotypicFeature    D002292
2  DiseaseOrPhenotypicFeature    D009369
3              ChemicalEntity    D025101
4              ChemicalEntity    D011732

In [3]:
unique_pair_relation["Identity_Type"].value_counts()

GeneOrGeneProduct             8609
ChemicalEntity                4708
DiseaseOrPhenotypicFeature    3210
SequenceVariant               2187
OrganismTaxon                 1022
CellLine                       652
Name: Identity_Type, dtype: int64

In [4]:
pair_relation_best.head()

,Relation Type,Presion,Recall,F1_Score,name_run
0,ChemicalEntity|ChemicalEntity|Association:,0.410959,0.306122,0.350877,run2
1,ChemicalEntity|ChemicalEntity|Bind:,0.000000,0.000000,0.000000,run1
2,ChemicalEntity|ChemicalEntity|Comparison:,0.500000,0.230769,0.315789,run2
3,ChemicalEntity|ChemicalEntity|Conversion:,0.700000,0.538462,0.608696,run2
4,ChemicalEntity|ChemicalEntity|Cotreatment:,0.912698,0.684524,0.782313,run3

In [5]:
# import pandas as pd
# import os

# # file_path = "/Users/benphan/NCKU/IIR-Lab/BioCreative/Data/Demo_Probability.pubtator"
# #file_path = "/Users/benphan/NCKU/IIR-Lab/BioCreative/Data/add_pair_entities_All_no_none_novel.pubtator"
# dir = "/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/Subtask1_Submission"
# # Initialize data collection list
# list_file = os.listdir(dir)

# list_data = []
# for file_path in list_file: 
#     file_path = os.path.join(dir, file_path)  
# # Open and process the file
#     with open(file_path, 'r') as file:
#         for line in file:
#             fields = line.strip().split('\t')
#             if len(fields) == 6:
#                 list_data.append([fields[4], fields[5]])

# unique_pair_relation = pd.DataFrame(list_data, columns=["Identity_Type", "Identifier"])
# # Assuming you have a DataFrame called unique_pair_relation
# # Remove rows with duplicate "Identifier" values
# unique_pair_relation = unique_pair_relation.drop_duplicates(subset="Identifier")

# # Reset the index of the resulting DataFrame
# unique_pair_relation = unique_pair_relation.reset_index(drop=True)
# # Save the unique_pair_relation DataFrame to a text file

# split_rows = []
# for index, row in unique_pair_relation.iterrows():
#     identifiers = row["Identifier"].split(",")  # Split the comma-separated identifiers
#     for identifier in identifiers:
#         split_rows.append([row["Identity_Type"], identifier])

# # Create a new DataFrame with the split rows
# new_unique_pair_relation = pd.DataFrame(split_rows, columns=["Identity_Type", "Identifier"])
# new_unique_pair_relation.drop_duplicates(subset="Identifier") 
# new_unique_pair_relation = new_unique_pair_relation.reset_index(drop=True)
# new_unique_pair_relation.to_csv('/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/unique_pair_relation.txt', sep='\t', index=False)

In [6]:
# import pandas as pd
# import os

# # file_path = "/Users/benphan/NCKU/IIR-Lab/BioCreative/Data/Demo_Probability.pubtator"
# #file_path = "/Users/benphan/NCKU/IIR-Lab/BioCreative/Data/add_pair_entities_All_no_none_novel.pubtator"
# dir = "/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/Subtask1_Submission"
# # Initialize data collection list
# list_file = os.listdir(dir)
# list_file.sort()

# data_frame = []
# for file_path in list_file: 
#     list_data = []
#     file_path = os.path.join(dir, file_path)  
# # Open and process the file
#     with open(file_path, 'r') as file:

#         for line in file:
#             fields = line.strip().split('\t')
#             if len(fields) == 5:
#                 list_data.append([fields[0], fields[1], fields[2], fields[3], fields[4] ])
#     data_frame.append(pd.DataFrame(list_data, columns=["doc_id", "Relation_Type", "Identifier_1", "Identifier_2", "Novelty"]))

In [7]:
# # Assuming you have a DataFrame called unique_pair_relation

# def gen_format_relation_type(Identifier_1, Identifier_2, Relation_Type):
#   # Use .loc to filter the DataFrame by the specified Identifier
#   result1 = unique_pair_relation.loc[unique_pair_relation["Identifier"] == Identifier_1, "Identity_Type"].iloc[0]

#   result2 = unique_pair_relation.loc[unique_pair_relation["Identifier"] == Identifier_2, "Identity_Type"].iloc[0]

#   output1 = result1 + "|" + result2 

#   return output1 + "|" + Relation_Type + ":"  
# for i in range(4): 
#   data_frame[i][['New_Column_1', 'New_Column_2']] = data_frame[i].apply(lambda row: gen_format_relation_type(row['Identifier_1'], row['Identifier_2'], row['Relation_Type']), axis=1, result_type='expand')

# for i in range(4):
#   data_frame[i].to_csv(f'/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/Subtask1_add_2_column/Updated_Subtask1_Run{i+1}_Add_2_Column.txt', sep='\t', index=False)

In [8]:
# Assuming you have a DataFrame called unique_pair_relation
# def gen_format_relation_type(Identifier_1, Identifier_2, Relation_Type):
#     # Use .loc to filter the DataFrame by the specified Identifier
#     result1 = unique_pair_relation.loc[unique_pair_relation["Identifier"] == Identifier_1, "Identity_Type"].iloc[0]
#     result2 = unique_pair_relation.loc[unique_pair_relation["Identifier"] == Identifier_2, "Identity_Type"].iloc[0]

#     # Define the mappings
#     mappings = {
#         "DiseaseOrPhenotypicFeature|ChemicalEntity": "ChemicalEntity|DiseaseOrPhenotypicFeature",
#         "GeneOrGeneProduct|ChemicalEntity": "ChemicalEntity|GeneOrGeneProduct",
#         "SequenceVariant|ChemicalEntity": "ChemicalEntity|SequenceVariant",
#         "GeneOrGeneProduct|DiseaseOrPhenotypicFeature": "DiseaseOrPhenotypicFeature|GeneOrGeneProduct",
#         "SequenceVariant|DiseaseOrPhenotypicFeature": "DiseaseOrPhenotypicFeature|SequenceVariant"
#     }

#     # Check if the combination needs to be mapped
#     combination = f"{result1}|{result2}"
#     if combination in mappings:
#         output1 = mappings[combination]
#     else:
#         output1 = combination

#     return output1 + "|" + Relation_Type + ":"

# for i in range(4): 
#   data_frame[i]['New_Column_1'] = data_frame[i].apply(lambda row: gen_format_relation_type(row['Identifier_1'], row['Identifier_2'], row['Relation_Type']), axis=1, result_type='expand')

# for i in range(4):
#   data_frame[i].to_csv(f'/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/Subtask1_add_2_column/Updated_Subtask1_Run{i+1}_Add_2_Column.txt', sep='\t', index=False)

In [9]:
input_dir = "/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/Subtask1_add_2_column"
list_file_data = os.listdir(input_dir) 
list_file_data.sort()
data_frame = [None,None,None,None]
for i in range(4):
  data_frame[i] = pd.read_csv(os.path.join(input_dir, list_file_data[i]), sep='\t')

In [10]:
data_frame[0].head()

,doc_id,Relation_Type,Identifier_1,Identifier_2,Novelty,New_Column_1
0,35366005,Negative_Correlation,D011732,D002292,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Nega...
1,35366005,Association,D025101,D002292,No,ChemicalEntity|DiseaseOrPhenotypicFeature|Asso...
2,35366005,Association,D006710,D002292,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Asso...
3,35366005,Negative_Correlation,D003545,D002292,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Nega...
4,36359868,Negative_Correlation,D002945,D009369,No,ChemicalEntity|DiseaseOrPhenotypicFeature|Nega...

In [11]:
data_frame[0]["New_Column_1"].unique().tolist()

['ChemicalEntity|DiseaseOrPhenotypicFeature|Negative_Correlation:',
 'ChemicalEntity|DiseaseOrPhenotypicFeature|Association:',
 'ChemicalEntity|GeneOrGeneProduct|Positive_Correlation:',
 'ChemicalEntity|DiseaseOrPhenotypicFeature|Positive_Correlation:',
 'DiseaseOrPhenotypicFeature|GeneOrGeneProduct|Positive_Correlation:',
 'DiseaseOrPhenotypicFeature|SequenceVariant|Positive_Correlation:',
 'DiseaseOrPhenotypicFeature|GeneOrGeneProduct|Association:',
 'ChemicalEntity|GeneOrGeneProduct|Association:',
 'ChemicalEntity|ChemicalEntity|Association:',
 'ChemicalEntity|GeneOrGeneProduct|Negative_Correlation:',
 'GeneOrGeneProduct|GeneOrGeneProduct|Positive_Correlation:',
 'GeneOrGeneProduct|GeneOrGeneProduct|Association:',
 'DiseaseOrPhenotypicFeature|GeneOrGeneProduct|Negative_Correlation:',
 'ChemicalEntity|ChemicalEntity|Cotreatment:',
 'GeneOrGeneProduct|GeneOrGeneProduct|Negative_Correlation:',
 'DiseaseOrPhenotypicFeature|SequenceVariant|Association:',
 'ChemicalEntity|ChemicalEntity|Positive_Correlation:',
 'GeneOrGeneProduct|GeneOrGeneProduct|Bind:',
 'ChemicalEntity|SequenceVariant|Negative_Correlation:',
 'ChemicalEntity|ChemicalEntity|Negative_Correlation:',
 'ChemicalEntity|ChemicalEntity|Comparison:',
 'ChemicalEntity|GeneOrGeneProduct|Cotreatment:',
 'ChemicalEntity|ChemicalEntity|Conversion:',
 'ChemicalEntity|ChemicalEntity|Drug_Interaction:',
 'ChemicalEntity|GeneOrGeneProduct|Bind:',
 'GeneOrGeneProduct|SequenceVariant|Positive_Correlation:',
 'ChemicalEntity|SequenceVariant|Association:',
 'ChemicalEntity|GeneOrGeneProduct|Comparison:',
 'ChemicalEntity|SequenceVariant|Positive_Correlation:',
 'DiseaseOrPhenotypicFeature|SequenceVariant|Negative_Correlation:',
 'SequenceVariant|GeneOrGeneProduct|Association:',
 'GeneOrGeneProduct|SequenceVariant|Bind:',
 'DiseaseOrPhenotypicFeature|GeneOrGeneProduct|Bind:',
 'DiseaseOrPhenotypicFeature|OrganismTaxon|Association:',
 'GeneOrGeneProduct|SequenceVariant|Association:',
 'GeneOrGeneProduct|SequenceVariant|Negative_Correlation:',
 'GeneOrGeneProduct|OrganismTaxon|Negative_Correlation:',
 'ChemicalEntity|ChemicalEntity|Bind:',
 'GeneOrGeneProduct|OrganismTaxon|Positive_Correlation:',
 'ChemicalEntity|OrganismTaxon|Negative_Correlation:',
 'SequenceVariant|GeneOrGeneProduct|Negative_Correlation:',
 'GeneOrGeneProduct|GeneOrGeneProduct|Drug_Interaction:',
 'DiseaseOrPhenotypicFeature|GeneOrGeneProduct|Drug_Interaction:',
 'ChemicalEntity|OrganismTaxon|Positive_Correlation:',
 'OrganismTaxon|GeneOrGeneProduct|Positive_Correlation:',
 'OrganismTaxon|GeneOrGeneProduct|Negative_Correlation:',
 'OrganismTaxon|GeneOrGeneProduct|Bind:',
 'OrganismTaxon|DiseaseOrPhenotypicFeature|Association:',
 'OrganismTaxon|ChemicalEntity|Association:',
 'GeneOrGeneProduct|OrganismTaxon|Association:',
 'ChemicalEntity|OrganismTaxon|Association:',
 'SequenceVariant|OrganismTaxon|Positive_Correlation:',
 'OrganismTaxon|GeneOrGeneProduct|Association:',
 'SequenceVariant|GeneOrGeneProduct|Positive_Correlation:',
 'OrganismTaxon|SequenceVariant|Positive_Correlation:',
 'ChemicalEntity|DiseaseOrPhenotypicFeature|Cotreatment:',
 'DiseaseOrPhenotypicFeature|OrganismTaxon|Positive_Correlation:',
 'SequenceVariant|SequenceVariant|Association:',
 'ChemicalEntity|DiseaseOrPhenotypicFeature|Drug_Interaction:',
 'ChemicalEntity|DiseaseOrPhenotypicFeature|Bind:',
 'GeneOrGeneProduct|GeneOrGeneProduct|Cotreatment:',
 'DiseaseOrPhenotypicFeature|OrganismTaxon|Negative_Correlation:',
 'ChemicalEntity|DiseaseOrPhenotypicFeature|Comparison:']

In [12]:
data_frame[0]["Relation_Type"].value_counts()

Association             27943
Negative_Correlation    12511
Positive_Correlation    10031
Cotreatment               594
Bind                      562
Comparison                217
Conversion                 56
Drug_Interaction           24
Name: Relation_Type, dtype: int64

In [ ]:
pair_relation_best

In [13]:
pair_relation = "ChemicalEntity|ChemicalEntity|Association:"
def get_name_run(pair_relation):
  try: 
    return pair_relation_best.loc[pair_relation_best["Relation Type"] == pair_relation, "name_run"].iloc[0]
  except: 
    return "base_best_run"

In [14]:
# pair_relation = "ChemicalEntity|ChemicalEntity|Association"
get_name_run(pair_relation)

'run2'

In [15]:
for i in range(4):  
  data_frame[i]['name_run'] = data_frame[i]['New_Column_1'].apply(get_name_run)

In [16]:
data_frame[1]

,doc_id,Relation_Type,Identifier_1,Identifier_2,Novelty,New_Column_1,name_run
0,35366005,Negative_Correlation,D011732,D002292,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Nega...,run1
1,35366005,Association,D025101,D002292,No,ChemicalEntity|DiseaseOrPhenotypicFeature|Asso...,run2
2,35366005,Association,D006710,D002292,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Asso...,run2
3,35366005,Negative_Correlation,D003545,D002292,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Nega...,run1
4,36415537,Association,D002289,29126,No,DiseaseOrPhenotypicFeature|GeneOrGeneProduct|A...,run1
...,...,...,...,...,...,...,...
54444,35394679,Association,C404987,D011230,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Asso...,run2
54445,35394679,Negative_Correlation,D059808,D009369,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Nega...,run1
54446,35394679,Association,C404987,D009369,Novel,ChemicalEntity|DiseaseOrPhenotypicFeature|Asso...,run2
54447,36291918,Association,D009369,10724,Novel,DiseaseOrPhenotypicFeature|GeneOrGeneProduct|A...,run1
54448,36291918,Association,D009369,8473,Novel,DiseaseOrPhenotypicFeature|GeneOrGeneProduct|A...,run1

In [23]:
data_frame[0]["name_run"].value_counts()

run1             29775
run2             13846
run3              7914
base_best_run      367
run4                36
Name: name_run, dtype: int64

In [17]:
data_frame_run1 = data_frame[0].loc[data_frame[0]["name_run"] == "run1"]
data_frame_run1.reset_index(drop=True, inplace=True)

data_frame_run2 = data_frame[1].loc[data_frame[1]["name_run"] == "run2"]
data_frame_run2.reset_index(drop=True, inplace=True)

data_frame_run3 = data_frame[2].loc[data_frame[2]["name_run"] == "run3"]
data_frame_run3.reset_index(drop=True, inplace=True)

data_frame_run4 = data_frame[3].loc[data_frame[3]["name_run"] == "run4"]
data_frame_run4.reset_index(drop=True, inplace=True)

data_frame_run5 = data_frame[1].loc[data_frame[1]["name_run"] == "base_best_run"]
data_frame_run5.reset_index(drop=True, inplace=True)

In [19]:
data_frame_run5

,doc_id,Relation_Type,Identifier_1,Identifier_2,Novelty,New_Column_1,name_run
0,32890629,Positive_Correlation,p|SUB|S|897|E,998,Novel,SequenceVariant|GeneOrGeneProduct|Positive_Cor...,base_best_run
1,35895872,Positive_Correlation,558,rs121434569,Novel,GeneOrGeneProduct|SequenceVariant|Positive_Cor...,base_best_run
2,32301865,Positive_Correlation,64816,rs62471956,Novel,GeneOrGeneProduct|SequenceVariant|Positive_Cor...,base_best_run
3,36407151,Comparison,D010672,3630,Novel,ChemicalEntity|GeneOrGeneProduct|Comparison:,base_best_run
4,36350735,Comparison,D005947,493804,No,ChemicalEntity|GeneOrGeneProduct|Comparison:,base_best_run
...,...,...,...,...,...,...,...
377,36309505,Association,D010198,1736,No,DiseaseOrPhenotypicFeature|OrganismTaxon|Assoc...,base_best_run
378,36309505,Association,D000080983,1736,No,DiseaseOrPhenotypicFeature|OrganismTaxon|Assoc...,base_best_run
379,36505399,Negative_Correlation,rs121434568,925,Novel,SequenceVariant|GeneOrGeneProduct|Negative_Cor...,base_best_run
380,36770730,Negative_Correlation,D000077337,1351,Novel,ChemicalEntity|OrganismTaxon|Negative_Correlat...,base_best_run
381,36770730,Positive_Correlation,9734,1351,Novel,GeneOrGeneProduct|OrganismTaxon|Positive_Corre...,base_best_run

In [ ]:
data_frame_run2["name_run"].value_counts()

In [24]:
data_frames_to_merge = [data_frame_run1, data_frame_run2, data_frame_run3, data_frame_run4, data_frame_run5]

# Concatenate the DataFrames along the rows (axis=0)
data_frame_final_1 = pd.concat(data_frames_to_merge, axis=0, ignore_index=True)
data_frame_final_1.sort_values(by='doc_id', inplace=True)
data_frame_final_1.reset_index(drop=True, inplace=True)
data_frame_final_1.drop(columns=["New_Column_1", "name_run"],inplace=True)

In [25]:
data_frame_final_1.head()

     doc_id         Relation_Type Identifier_1 Identifier_2 Novelty
0  10402574  Negative_Correlation      D008055      D003327      No
1  11005078  Negative_Correlation      D012254      D019698   Novel
2  11005078  Negative_Correlation      D019259      D019694      No
3  11005078  Negative_Correlation      D019259      D006509      No
4  11005078  Negative_Correlation      D012254      D006521      No

In [32]:
def export_relation_type(doc_id): 
  doc_id = int(doc_id)
  data = data_frame_final_1.loc[data_frame_final_1["doc_id"] == doc_id].values.tolist()
  if len(data) > 0: 
    return [[str(item) for item in sublist] for sublist in data]
  else : 
    return [['']]

In [33]:
export_relation_type(34189746)

[['34189746', 'Association', 'D006025', 'D009083', 'No'],
 ['34189746', 'Association', 'D009083', '3425', 'No'],
 ['34189746', 'Association', 'D006025', '3425', 'No']]

In [34]:
data_frame_final_1.to_csv('/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/data_relation_pair/data_frame_2.txt', sep='\t', index=False)

In [35]:
import os
file_path = "/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/Subtask1_Submission/Updated_Subtask1_Run2.pubtator"

# Step 1: Open the file
documents = []
entities = []
pair_entities = []
id_document = 0 
raw_data = []
with open(file_path, 'r') as file:
    lines = file.readlines()
    # Step 2: Read and process the contents
for i, line in enumerate(lines):
    fields = line.strip().split('\t')
    if  i == 0 and '|t|' in fields[0]:
        position = fields[0].find('|t|')
        id_document = fields[0][:position]
        raw_data.append(fields)  
        print(id_document) 
    elif i == len(lines) - 1:
        raw_data.append(fields) 
        documents.append(raw_data)
        print(fields)
    elif '|t|' in fields[0]:
        position = fields[0].find('|t|')
        id_document = fields[0][:position]
        documents.append(raw_data)
        raw_data = [] 
        raw_data.append(fields) 
    elif '|a|' in fields[0]:
        position = fields[0].find('|a|')
        if id_document == fields[0][:position] : 
            raw_data.append(fields)  
    elif id_document == fields[0]: 
        raw_data.append(fields)

36713719
['']

In [36]:
new_documents = []

for i, document in enumerate(documents):
  new_document = []
  for j, fields in enumerate(document):
    if len(fields) == 5:
      pass 
    else: 
      new_document.append(fields)
  new_documents.append(new_document)
new_documents[-1].pop(-1)
new_documents[-1][-1]

['36291918', '1499', '1505', 'cancer', 'DiseaseOrPhenotypicFeature', 'D009369']

In [37]:
document_ids = []
id_document = ""
for i, document_new in enumerate(new_documents):
  for j, fields in enumerate(document_new):
      if '|t|' in fields[0]:
          position = fields[0].find('|t|')
          id_document = fields[0][:position]
          datas = export_relation_type(id_document)  
          if len(datas) > 0:
            for data in datas:
              new_documents[i].append(data)

In [ ]:
lines_new = []
for document in new_documents:
    for i, fields in enumerate(document):
       line = ""
       for j, field in enumerate(fields):
          if j == 0: 
             line = line + field    
          else: 
            line = line + "\t" + field
       line = line + "\n" 
       lines_new.append(line) 
    lines_new.append('\n')

with open("/Users/benphan/NCKU/IIR-Lab/BioCreative/6_10_final/TestSet/Final_Submit_Subtask1/subtask1_process_statistics_run2.pubtator", "w") as file: 
  file.writelines(lines_new)